direct_mapped_cache: direct_mapped_cache.cpp
	g++ -o direct_mapped_cache direct_mapped_cache.cpp -I.
	
direct_mapped_cache_lru: direct_mapped_cache_lru.cpp
	g++ -o direct_mapped_cache_lru direct_mapped_cache_lru.cpp -I.
